version: "2"
checks:
  argument-count:
    enabled: true
  complexity:
    enabled: true
  duplication:
    enabled: true
  bug-risk:
    enabled: true

engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
  maintainability:
    enabled: true

ratings:
  paths:
    - "**.js"
    - "**.ts"

exclude_patterns:
  - "node_modules/**"
  - "tests/**"
